In [2]:
import numpy as np
b=np.array([1,2,3])
print(b)
c=np.array([[1,2,3],[4,5,6]])
print(c)
d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [ ]:
np.arange(1,15)   


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [12]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
np.random.random((3,4))

array([[0.2801716 , 0.53173043, 0.6791713 , 0.95756328],
       [0.85266996, 0.04389601, 0.21694776, 0.11862363],
       [0.34615399, 0.28842447, 0.22037787, 0.66559674]])

In [16]:
np.linspace(-10,10,9)

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [20]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [23]:
a2.ndim

2

In [24]:
a3.shape

(2, 2, 2)

In [25]:
a2.size

12

In [26]:
a2.itemsize

8

In [27]:
a3.dtype

dtype('int64')

In [30]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [31]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])