In [3]:
import numpy as np
b=np.array([1,2,3])
print(b)
c=np.array([[1,2,3],[4,5,6]])
print(c)
d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [4]:
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [5]:
np.arange(1,15)   


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
np.random.random((3,4))

array([[0.26488257, 0.19772407, 0.94058567, 0.04689708],
       [0.82586574, 0.18712824, 0.33594858, 0.07574817],
       [0.9722444 , 0.4022885 , 0.58164681, 0.53733625]])

In [8]:
np.linspace(-10,10,9)

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [11]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [12]:
a2.ndim

2

In [13]:
a3.shape

(2, 2, 2)

In [14]:
a2.size

12

In [15]:
a2.itemsize

8

In [16]:
a3.dtype

dtype('int64')

In [17]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [25]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [28]:
a1*2
a1+2
a1*8

array([[ 0,  8, 16, 24],
       [32, 40, 48, 56],
       [64, 72, 80, 88]])

In [30]:
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [47]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[20., 62., 73.],
       [25., 74., 50.],
       [44., 66., 48.]])

In [48]:
np.max(a1)

np.float64(74.0)

In [49]:
np.min(a1)

np.float64(20.0)

In [50]:
np.sum(a1)

np.float64(462.0)

In [51]:
np.prod(a1)

np.float64(1167143155200000.0)

In [52]:
np.max(a1,axis=0)

array([44., 74., 73.])

In [54]:
np.min(a1,axis=1)

array([20., 25., 44.])

In [55]:
np.mean(a1)

np.float64(51.333333333333336)

In [56]:
np.std(a1)

np.float64(18.421002506197464)

In [58]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12).reshape(4,3)
np.dot(a2,a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [62]:
np.round(np.random.random((2,3))*100)

array([[ 1., 88., 97.],
       [76., 23., 65.]])

In [66]:
a1=np.arange(10)
print(a1)
a2=np.arange(12).reshape(3,4)
print(a2)
a3=np.arange(8).reshape(2,2,2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [64]:
a1[-1]

np.int64(9)

In [65]:
a2[-1]

array([ 8,  9, 10, 11])

In [67]:
a2[-1,-1]

np.int64(11)

In [68]:
a3[1,0,1]

np.int64(5)

In [70]:
a1[2:5]

array([2, 3, 4])

In [71]:
a2[0,:]

array([0, 1, 2, 3])

In [72]:
a2[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [73]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [75]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [76]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [81]:
a4=np.round(np.random.random((3,3,3))*100)

In [82]:
a4

array([[[33., 63.,  8.],
        [ 9., 96., 17.],
        [83.,  8.,  9.]],

       [[14., 43.,  3.],
        [10., 40., 41.],
        [79., 37., 59.]],

       [[49., 95., 49.],
        [29., 10., 27.],
        [79., 18., 64.]]])

In [85]:
a4[1,:,:]

array([[14., 43.,  3.],
       [10., 40., 41.],
       [79., 37., 59.]])

In [86]:
a4[0,1,:]

array([ 9., 96., 17.])

In [87]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
for i in a1:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [95]:
for i in a2:
    print(i,end=" ")

[0 1 2 3] [4 5 6 7] [ 8  9 10 11] 

In [96]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [97]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [99]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
np.transpose(a3)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [103]:
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [104]:
s1=np.arange(12).reshape(3,4)
s2=np.arange(12,24).reshape(3,4)
s3=np.arange(24,36).reshape(3,4)


In [105]:
s1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
s2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [107]:
s3

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [112]:
r1=np.hstack((s1,s2,s3))
r1

array([[ 0,  1,  2,  3, 12, 13, 14, 15, 24, 25, 26, 27],
       [ 4,  5,  6,  7, 16, 17, 18, 19, 28, 29, 30, 31],
       [ 8,  9, 10, 11, 20, 21, 22, 23, 32, 33, 34, 35]])

In [113]:
r2=np.vstack((s1,s2,s3))
r2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [114]:
np.hsplit(r1,2)

[array([[ 0,  1,  2,  3, 12, 13],
        [ 4,  5,  6,  7, 16, 17],
        [ 8,  9, 10, 11, 20, 21]]),
 array([[14, 15, 24, 25, 26, 27],
        [18, 19, 28, 29, 30, 31],
        [22, 23, 32, 33, 34, 35]])]

In [117]:
np.vsplit(r2,3)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]])]