**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [8]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [9]:
#Code here
a=np.nan*np.empty(10)
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [10]:
#Code here
a,b=map(int,(input("Enter a and b: ").split()))
m1=np.random.random((a,b))
print(m1)
print(np.mean(m1))

[[0.48989956 0.44423205 0.07714456 0.22806919]
 [0.09316604 0.00189981 0.71670503 0.93834016]
 [0.9828415  0.76360371 0.83856659 0.44942685]]
0.501991254391367


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [11]:
#Code here
m2=np.zeros((a,b))
m2[0,:]=1
m2[-1,:]=1
m2[:,0]=1
m2[:,-1]=1
m2

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [12]:
#Code here
m3=np.linspace(0,1,12)[1:-1]
m3

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [13]:
#Code here
m4=np.eye(3)
m4
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [14]:
#Code here
m5=np.zeros((5,5))
m6=np.arange(5)
m6
m5+=m6
m5

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [15]:
#code here
m7=np.round(np.random.random((10,2))*100)
m7
point=np.array([2,3])
difference=m7-point
np.sqrt(np.sum(difference**2,axis=1)).astype(int)

array([ 70,  72,  57,  85,  83, 103,  64,  85,  81,  62])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [16]:
#Code here
m8=np.arange(6*7*8).reshape(6,7,8)
m8
i,j,k=99//(7*8),(99//8)%7,99%8
print(i,j,k)

1 5 3


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [17]:
#Code here
# ip=input("enter numbers:").split()
# m9=np.array(ip,dtype=float)
# m9
# m10=m9[-1::-1]
# m10

ip=input().strip().split()
np.array(ip[::-1],dtype=np.float32)

array([], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [18]:
#Code here
a=np.ones((6,7))
a.size

42

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [19]:
#Code here
vec1=np.random.random((7,))*100
def softmax(arr):
    if type(arr)!=np.ndarray:
        print("Array type must be numpy")
        return
    if np.ndim(arr)!=1:
        print("Array must be 1-D")
        return
    return np.exp(arr)/np.sum(np.exp(arr))
print(softmax(vec1))

[6.09702162e-36 9.47296944e-15 2.78679883e-05 9.99972132e-01
 6.60137756e-37 1.59701739e-11 1.42018777e-24]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [20]:
#Code here
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)

a = np.arange(10).reshape(2, -1)
print("a=",a)
b = np.repeat(1, 10).reshape(2, -1)
print("b=",b)
print(vertical_stack(a,b))
c = np.random.random((2,5))
print("c=", c)
vertical_stack(a,b,c)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.05370855 0.20082278 0.29256866 0.35285143 0.56377563]
 [0.30705847 0.87529589 0.47839206 0.21896113 0.85646867]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.05370855, 0.20082278, 0.29256866, 0.35285143, 0.56377563],
       [0.30705847, 0.87529589, 0.47839206, 0.21896113, 0.85646867]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [37]:
#Code here
def date_array(start, end):
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("start and end must be strings")
    
    start_date = np.datetime64(start, 'D')
    end_date = np.datetime64(end, 'D')
    n_days = (end_date - start_date).astype(int) + 1  # inclusive
    
    return start_date + np.arange(n_days)


date_array(start = '2020-09-15', end = '2020-09-25')


array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24', '2020-09-25'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [39]:
#code here 
a=np.random.random((6,8))
a=a-np.mean(a,keepdims=True,axis=1)
a

array([[-0.53204704, -0.37189312,  0.15072843, -0.12040136,  0.37849642,
         0.16894814,  0.36848826, -0.04231972],
       [ 0.05301315,  0.14756237, -0.25848226, -0.28341967, -0.16482464,
        -0.2188525 ,  0.19314654,  0.53185701],
       [ 0.32906356, -0.35729213,  0.11377832, -0.47430731, -0.0030747 ,
         0.39510151, -0.15140174,  0.1481325 ],
       [ 0.19821776,  0.3279188 ,  0.14966521,  0.27499983, -0.54337493,
         0.09867301, -0.0225692 , -0.48353048],
       [-0.27499271, -0.39199235, -0.15467048,  0.26106   ,  0.24826756,
        -0.00098155,  0.45262563, -0.1393161 ],
       [ 0.20727322, -0.37944658,  0.2155671 ,  0.27992621,  0.23690479,
        -0.00294244, -0.43477536, -0.12250695]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [23]:
#Code here

###`Q-16:` Replace odd elements in arrays with -1.

In [24]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [25]:
#Code here

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [26]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[6214, 5482,  868, 4766, 9374],
       [8005, 4076,  794, 2259, 1247],
       [5643, 7442,  666, 5233, 7165],
       [9879, 8058, 5148, 5725, 8374],
       [9103, 4054, 3678, 4419, 6458],
       [3845, 9008,  773, 1765, 4211],
       [ 924, 9161, 6437, 3993, 9530],
       [6540, 9886, 7427, 1229, 7309]])

In [27]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [28]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [29]:
#code here